extends:
  - stylelint-config-standard
  - stylelint-config-idiomatic-order
  - stylelint-prettier
overrides:
  - files:
      - 'src/**/*.{ts,tsx}'
    customSyntax: '@stylelint/postcss-css-in-js'
rules:
  selector-id-pattern: null
  selector-class-pattern: null
  annotation-no-unknown: null
#  keyframe-name-pattern: null
#  scss/dollar-variable-pattern: null
#  scss/percentage-placeholder-pattern: null
#  scss/at-extend-no-missing-placeholder: null
