name: deploy develop

on: 
  push:
    branches:
      - 'develop'
    paths:
      - 'build.txt'
      -  '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gatsby build
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: setting environment
        run: |
          touch .env
          echo accessToken=${{secrets.DEBUG_ACCESS_TOKEN}} >> .env
          echo spaceId=${{secrets.DEBUG_SPACE_ID}} >> .env
      - run: npm ci
      - run: npm run build
      - run: |
          pwd
          ls