name: deploy develop

on: 
  push:
    tags:
      - 'dev*'

env:
  ACCESSTOKEN: ${{secrets.DEVELOP_ACCESSTOKEN}}
  SPACEID: ${{secrets.DEVELOP_SPACEID}}
  SITEURL: ${{secrets.DEVELOP_SITEURL}}
  GOOGLE_ANALYTICS: ${{secrets.DEVELOP_GOOGLE_ANALYTICS}}

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: gatsby build
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: atrevete
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}